version: "3"
services:
  development:
    container_name: development
    build: .
    volumes:
      - .:/development
    ports:
      - "8089:8089"

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379